const cuid = require("cuid");

// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Organization = sequelize.define(
    "organization",
    {
      id: {
        type: DataTypes.STRING,
        primaryKey: true,
        defaultValue: cuid(),
      },
      name: {
        type: DataTypes.STRING,
      },
      alias: {
        type: DataTypes.STRING,
      },
      createdAt: {
        type: DataTypes.DATE,
        defaultValue: Sequelize.literal("now()"),
      },
      updatedAt: {
        type: DataTypes.DATE,
        defaultValue: Sequelize.literal("now()"),
      },
      deletedAt: {
        type: DataTypes.DATE,
      },
    },
    {
      tableName: "organization",
      schema: process.env.DATABASE_SCHEMA,
      paranoid: true,
      isSoftDeleted: true,
    }
  );

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Organization.associate = (models) => {
    Organization.hasMany(models.userToOrganization, {
      foreignKey: {
        name: "organizationId",
        field: "organizationId",
      },
      as: "userToOrganizations",
    });
    Organization.hasOne(models.controllerContact, {
      foreignKey: {
        name: "organizationId",
        field: "organizationId",
      },
      as: "controller",
    });
    Organization.belongsTo(models.address);
    Organization.belongsTo(models.industryClassification);
  };

  return Organization;
};
